"""C3A1 strategy specifications for the rapid research platform."""

from __future__ import annotations

from src.strategies.c3a1_signals import (
    breakout_persistence,
    downside_beta,
    improving_liquidity,
    low_amihud_illiquidity,
    low_gap_risk,
    low_max_effect,
    low_rolling_drawdown,
    low_tail_loss,
    low_downside_volatility,
    price_efficiency,
    relative_strength_12_1,
    relative_strength_6_1,
    residual_momentum_12_1,
    stable_dollar_volume,
    trend_quality,
    volatility_adjusted_momentum,
    volume_confirmed_trend,
)
from src.strategies.strategy_factory import StrategySpec

C3A1_SPECS: tuple[StrategySpec, ...] = (
    StrategySpec("C3A1_001", "c3a1_001_residual_momentum_12_1_v1", "Residual Momentum 12-1",
                 "Long stocks with persistent SPY-adjusted residual momentum from month 12 through month 1.",
                 residual_momentum_12_1, 20, require_beta_history=False),
    StrategySpec("C3A1_002", "c3a1_002_relative_strength_12_1_v1", "Relative Strength 12-1",
                 "Long high 12-1 price momentum; short low 12-1 price momentum.",
                 relative_strength_12_1, 20),
    StrategySpec("C3A1_003", "c3a1_003_relative_strength_6_1_v1", "Relative Strength 6-1",
                 "Long high 6-1 price momentum; short low 6-1 price momentum.",
                 relative_strength_6_1, 20),
    StrategySpec("C3A1_004", "c3a1_004_volatility_adjusted_momentum_v1", "Volatility-Adjusted Momentum",
                 "Long high 12-1 momentum scaled by trailing realized volatility.",
                 volatility_adjusted_momentum, 20),
    StrategySpec("C3A1_005", "c3a1_005_trend_quality_v1", "Trend Quality",
                 "Long smooth positive log-price trends adjusted by residual volatility.",
                 trend_quality, 20),
    StrategySpec("C3A1_006", "c3a1_006_breakout_persistence_v1", "Breakout Persistence",
                 "Long names near trailing 252-day highs; short names far below highs.",
                 breakout_persistence, 20),
    StrategySpec("C3A1_007", "c3a1_007_low_downside_beta_v1", "Low Downside Beta",
                 "Long low SPY downside-beta names; short high downside-beta names.",
                 downside_beta, 20),
    StrategySpec("C3A1_008", "c3a1_008_low_downside_volatility_v1", "Low Downside Volatility",
                 "Long low trailing downside semideviation; short high downside semideviation.",
                 low_downside_volatility, 20),
    StrategySpec("C3A1_009", "c3a1_009_low_rolling_drawdown_v1", "Low Rolling Drawdown",
                 "Long stocks with smaller trailing drawdowns; short larger drawdowns.",
                 low_rolling_drawdown, 20),
    StrategySpec("C3A1_010", "c3a1_010_low_tail_loss_v1", "Low Tail Loss",
                 "Long smaller historical tail losses; short larger tail losses.",
                 low_tail_loss, 20),
    StrategySpec("C3A1_011", "c3a1_011_low_max_effect_v1", "Low MAX Effect",
                 "Long low recent maximum daily returns; short high MAX names.",
                 low_max_effect, 20),
    StrategySpec("C3A1_012", "c3a1_012_stable_dollar_volume_v1", "Stable Dollar Volume",
                 "Long stable trailing dollar volume; short unstable liquidity.",
                 stable_dollar_volume, 20),
    StrategySpec("C3A1_013", "c3a1_013_low_amihud_illiquidity_v1", "Low Amihud Illiquidity",
                 "Long lower Amihud illiquidity; short higher illiquidity.",
                 low_amihud_illiquidity, 20),
    StrategySpec("C3A1_014", "c3a1_014_improving_liquidity_v1", "Improving Liquidity",
                 "Long improving log dollar-volume trends; short deteriorating liquidity.",
                 improving_liquidity, 20),
    StrategySpec("C3A1_015", "c3a1_015_price_efficiency_v1", "Price Efficiency",
                 "Long efficient positive price paths; short inefficient or negative trends.",
                 price_efficiency, 20),
    StrategySpec("C3A1_016", "c3a1_016_volume_confirmed_trend_v1", "Volume-Confirmed Trend",
                 "Long medium-term momentum confirmed by dollar-volume expansion.",
                 volume_confirmed_trend, 20),
    StrategySpec("C3A1_017", "c3a1_017_low_gap_risk_v1", "Low Gap Risk",
                 "Long low overnight gap volatility; short high gap-risk names.",
                 low_gap_risk, 20),
)

C3A1_IDS = tuple(spec.strategy_id for spec in C3A1_SPECS)
